language: python
python:
  - "2.7"
before_script: "git clone https://github.com/freifunk/api.freifunk.net.git"
install: 
  - pip install jsonschema
  - pip install jsondiff
# command to run tests
script: python tests/test.py
