name: Check api directory

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout directory
    - uses: actions/checkout@v3
      name: checkout api specs
      with:
        repository: freifunk/api.freifunk.net
        path: api.freifunk.net
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analyze directory
      run: |
        python ./tests/test3.py
